.TH PCRE 3
.SH NAME
PCRE - Perl-compatible regular expressions
.SH SYNOPSIS
.rs
.sp
.B #include <pcre.h>
.PP
.SM
.br
.B int pcre_get_substring(const char *\fIsubject\fR, int *\fIovector\fR,
.ti +5n
.B int \fIstringcount\fR, int \fIstringnumber\fR,
.ti +5n
.B const char **\fIstringptr\fR);

.SH DESCRIPTION
.rs
.sp
This is a convenience function for extracting a captured substring. The
arguments are:

  \fIsubject\fR       Subject that has been successfully matched
  \fIovector\fR       Offset vector that \fBpcre_exec()\fR used
  \fIstringcount\fR   Value returned by \fBpcre_exec()\fR
  \fIstringnumber\fR  Number of the required substring
  \fIstringptr\fR     Where to put the string pointer

The yield is the length of the substring, PCRE_ERROR_NOMEMORY if sufficient
memory could not be obtained, or PCRE_ERROR_NOSUBSTRING if the string number is
invalid.

There is a complete description of the PCRE API in the
.\" HREF
\fBpcreapi\fR
.\"
page.
