.TH PCRE 3
.SH NAME
PCRE - Perl-compatible regular expressions
.SH SYNOPSIS
.rs
.sp
.B #include <pcre.h>
.PP
.SM
.br
.B char *pcre_version(void);

.SH DESCRIPTION
.rs
.sp
This function returns a character string that gives the version number of the
PCRE library, and its date of release.

There is a complete description of the PCRE API in the
.\" HREF
\fBpcreapi\fR
.\"
page.
