# When modifying this file, please validate using
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

ignore:
  - compare-for-test/*
  - libtests/*
  - qpdf/test*
  - qpdf/sizes.cc
  - qpdf/qpdf-*
  - qpdf/qpdfjob-*
