#!/bin/sh
./configure --disable-test-compare-images --enable-external-libs --enable-werror --with-windows-wordsize=32 --with-buildrules=mingw \
    CC=i686-w64-mingw32-gcc \
    CXX=i686-w64-mingw32-g++ \
    LD=i686-w64-mingw32-ld \
    AR=i686-w64-mingw32-ar \
    RANLIB=i686-w64-mingw32-ranlib \
    DLLTOOL=$(dirname $(type -p i686-w64-mingw32-gcc))/dlltool \
    STRIP=i686-w64-mingw32-strip \
    OBJDUMP=$(dirname $(type -p i686-w64-mingw32-gcc))/objdump \
    ${1+"$@"}
