#!/bin/sh
set -e
set -x
if echo $PATH | grep -q /mingw64; then
    wordsize=64
else
    wordsize=32
fi
CC=cl CXX="cl -TP -GR" ./configure --disable-test-compare-images --enable-external-libs --enable-werror --with-buildrules=msvc ${1+"$@"}
