#!/bin/sh
set -e
set -x
if echo $PATH | grep -q /mingw64; then
    wordsize=64
else
    wordsize=32
fi
./configure --disable-test-compare-images --enable-external-libs --enable-werror --with-windows-wordsize=$wordsize --with-buildrules=mingw ${1+"$@"}
