#!/bin/sh
if [ ! -d external-libs ]; then
   echo "Please extract qpdf-external-libs-bin.zip and try again"
   exit 2
fi

set -e
set -x
cwd=`pwd`
PATH=$cwd/libqpdf/build:$PATH

rm -rf install-mingw* install-msvc*

./config-mingw64
make -j8
make check install
make distclean
./config-mingw32
make -j8
make check install
make distclean

set +x

echo ''
echo 'Now run "./make_windows_releases-msvc 64" in a 64-bit MSVC environment'
echo 'and "./make_windows_releases-msvc 32" in a 32-bit MSVC environment.'
echo 'Then run "./make_windows_releases-finish".'
echo ''
