#!/bin/sh
if [ ! -d external-libs ]; then
   echo "Please extract qpdf-external-libs-bin.zip and try again"
   exit 2
fi

w=$1

if [ "$w" = "" ]; then
  echo "Usage: $0 {32|64}"
  exit 2
fi

set -e
set -x
cwd=`pwd`
PATH=$cwd/libqpdf/build:$PATH

./config-msvc $w
make -j8
make check install
make distclean
