//
// This file is automatically generated by generate_auto_job.
// Edits will be automatically overwritten if the build is
// run in maintainer mode.
//
char const* yn_choices[] = {"y", "n", 0};
char const* password_mode_choices[] = {"bytes", "hex-bytes", "unicode", "auto", 0};
char const* stream_data_choices[] = {"compress", "preserve", "uncompress", 0};
char const* decode_level_choices[] = {"none", "generalized", "specialized", "all", 0};
char const* object_streams_choices[] = {"disable", "preserve", "generate", 0};
char const* remove_unref_choices[] = {"auto", "yes", "no", 0};
char const* flatten_choices[] = {"all", "print", "screen", 0};
char const* json_key_choices[] = {"acroform", "attachments", "encrypt", "objectinfo", "objects", "outlines", "pagelabels", "pages", 0};
char const* print128_choices[] = {"full", "low", "none", 0};
char const* modify128_choices[] = {"all", "annotate", "form", "assembly", "none", 0};
