//
// This file is automatically generated by generate_auto_job.
// Edits will be automatically overwritten if the build is
// run in maintainer mode.
//
void beginInput();
void endInput();
void setupInputFileName(std::string const&);
void setupInputPassword(std::string const&);
void setupInputEmpty(std::string const&);
void beginOutput();
void endOutput();
void setupOutputFileName(std::string const&);
void setupOutputReplaceInput(std::string const&);
void beginOutputOptions();
void endOutputOptions();
void beginOutputOptionsEncrypt();
void endOutputOptionsEncrypt();
void setupOutputOptionsEncryptKeyLength(std::string const&);
void setupOutputOptionsEncryptUserPassword(std::string const&);
void setupOutputOptionsEncryptOwnerPassword(std::string const&);
void beginOutputOptionsEncrypt40Bit();
void endOutputOptionsEncrypt40Bit();
void beginOutputOptionsEncrypt128Bit();
void endOutputOptionsEncrypt128Bit();
void beginOutputOptionsEncrypt256Bit();
void endOutputOptionsEncrypt256Bit();
void beginOptions();
void endOptions();
void beginInspect();
void endInspect();
void beginTransform();
void endTransform();
void beginModify();
void endModify();
void beginModifyAddAttachment();
void endModifyAddAttachment();
void setupModifyAddAttachmentPath(std::string const&);
void beginModifyCopyAttachmentsFrom();
void endModifyCopyAttachmentsFrom();
void setupModifyCopyAttachmentsFromPath(std::string const&);
void setupModifyCopyAttachmentsFromPassword(std::string const&);
void beginModifyPages();
void endModifyPages();
void setupModifyPagesFile(std::string const&);
void setupModifyPagesPassword(std::string const&);
void setupModifyPagesRange(std::string const&);
void beginModifyOverlay();
void endModifyOverlay();
void setupModifyOverlayFile(std::string const&);
void setupModifyOverlayPassword(std::string const&);
void beginModifyUnderlay();
void endModifyUnderlay();
void setupModifyUnderlayFile(std::string const&);
void setupModifyUnderlayPassword(std::string const&);
