//
// This file is automatically generated by generate_auto_job.
// Edits will be automatically overwritten if the build is
// run in maintainer mode.
//
void beginInput(JSON);
void endInput();
void setupInputFilename(std::string const&);
void setupInputPassword(std::string const&);
void setupInputEmpty(std::string const&);
void beginOutput(JSON);
void endOutput();
void setupOutputFilename(std::string const&);
void setupOutputReplaceInput(std::string const&);
void beginOutputOptions(JSON);
void endOutputOptions();
void beginOutputOptionsEncrypt(JSON);
void endOutputOptionsEncrypt();
void setupOutputOptionsEncryptUserPassword(std::string const&);
void setupOutputOptionsEncryptOwnerPassword(std::string const&);
void beginOutputOptionsEncrypt40bit(JSON);
void endOutputOptionsEncrypt40bit();
void beginOutputOptionsEncrypt128bit(JSON);
void endOutputOptionsEncrypt128bit();
void beginOutputOptionsEncrypt256bit(JSON);
void endOutputOptionsEncrypt256bit();
void beginInspect(JSON);
void endInspect();
void beginOptions(JSON);
void endOptions();
void beginOptionsAddAttachment(JSON);
void endOptionsAddAttachment();
void setupOptionsAddAttachmentPath(std::string const&);
void beginOptionsCopyAttachmentsFrom(JSON);
void endOptionsCopyAttachmentsFrom();
void setupOptionsCopyAttachmentsFromPath(std::string const&);
void setupOptionsCopyAttachmentsFromPassword(std::string const&);
void beginOptionsPages(JSON);
void endOptionsPages();
void setupOptionsPagesFile(std::string const&);
void setupOptionsPagesPassword(std::string const&);
void setupOptionsPagesRange(std::string const&);
void beginOptionsOverlay(JSON);
void endOptionsOverlay();
void setupOptionsOverlayFile(std::string const&);
void setupOptionsOverlayPassword(std::string const&);
void beginOptionsUnderlay(JSON);
void endOptionsUnderlay();
void setupOptionsUnderlayFile(std::string const&);
void setupOptionsUnderlayPassword(std::string const&);
