//
// This file is automatically generated by generate_auto_job.
// Edits will be automatically overwritten if the build is
// run in maintainer mode.
//
// clang-format off
//
QPDF_DLL GlobalConfig* noDefaultLimits();
QPDF_DLL GlobalConfig* parserMaxContainerSize(std::string const& parameter);
QPDF_DLL GlobalConfig* parserMaxContainerSizeDamaged(std::string const& parameter);
QPDF_DLL GlobalConfig* parserMaxErrors(std::string const& parameter);
QPDF_DLL GlobalConfig* parserMaxNesting(std::string const& parameter);
QPDF_DLL GlobalConfig* maxStreamFilters(std::string const& parameter);
