//
// This file is automatically generated by generate_auto_job.
// Edits will be automatically overwritten if the build is
// run in maintainer mode.
//
QPDF_DLL UOConfig* to(char const* parameter);
QPDF_DLL UOConfig* from(char const* parameter);
QPDF_DLL UOConfig* repeat(char const* parameter);
QPDF_DLL UOConfig* password(char const* parameter);
