//
// This file is automatically generated by generate_auto_job.
// Edits will be automatically overwritten if the build is
// run in maintainer mode.
//
QPDF_DLL Config& end();
QPDF_DLL AttConfig& replace();
QPDF_DLL AttConfig& key(char const* parameter);
QPDF_DLL AttConfig& filename(char const* parameter);
QPDF_DLL AttConfig& creationdate(char const* parameter);
QPDF_DLL AttConfig& moddate(char const* parameter);
QPDF_DLL AttConfig& mimetype(char const* parameter);
QPDF_DLL AttConfig& description(char const* parameter);
