//
// This file is automatically generated by generate_auto_job.
// Edits will be automatically overwritten if the build is
// run in maintainer mode.
//
// clang-format off
//
QPDF_DLL AttConfig* replace();
QPDF_DLL AttConfig* key(std::string const& parameter);
QPDF_DLL AttConfig* filename(std::string const& parameter);
QPDF_DLL AttConfig* creationdate(std::string const& parameter);
QPDF_DLL AttConfig* moddate(std::string const& parameter);
QPDF_DLL AttConfig* mimetype(std::string const& parameter);
QPDF_DLL AttConfig* description(std::string const& parameter);
