//
// This file is automatically generated by generate_auto_job.
// Edits will be automatically overwritten if the build is
// run in maintainer mode.
//
QPDF_DLL EncConfig& extract(char const* parameter);
QPDF_DLL EncConfig& annotate(char const* parameter);
QPDF_DLL EncConfig& print(char const* parameter);
QPDF_DLL EncConfig& modify(char const* parameter);
QPDF_DLL EncConfig& cleartextMetadata();
QPDF_DLL EncConfig& forceV4();
QPDF_DLL EncConfig& accessibility(char const* parameter);
QPDF_DLL EncConfig& assemble(char const* parameter);
QPDF_DLL EncConfig& form(char const* parameter);
QPDF_DLL EncConfig& modifyOther(char const* parameter);
QPDF_DLL EncConfig& useAes(char const* parameter);
QPDF_DLL EncConfig& forceR5();
QPDF_DLL EncConfig& allowInsecure();
