#!/bin/sh
#
# Test that the installed qpdf CLI works. Requires the CLI and runtime
# libraries.
#
set -ex

TMP=$1
if [ ! -d "$TMP" ]; then
    echo 1>&2 "Usage: $0 tmp-dir"
    exit 2
fi

qpdf --version
qpdf --help
qpdf --check qpdf/qtest/qpdf/minimal.pdf
qpdf qpdf/qtest/qpdf/minimal.pdf --encrypt u o 256 -- $TMP/out.pdf
qpdf --check --password=u $TMP/out.pdf
