#!/bin/sh
# This script is used for valgrind testing. See README-maintainer.md.

# Create a suppressions file. This can be updated by running valgrind
# with --gen-suppressions=yes.
test -f /tmp/a.supp || cat > /tmp/a.supp <<EOF
{
   zlib1
   Memcheck:Cond
   fun:inflateReset2
   fun:inflateInit2_
}
{
   index
   Memcheck:Cond
   fun:index
   fun:expand_dynamic_string_token
   fun:_dl_map_object
   fun:map_doit
}
EOF

exec valgrind --suppressions=/tmp/a.supp -q \
   `dirname $0`/z/`basename $0` ${1+"$@"}
