#!/bin/bash
set -ex
cd $(dirname $0)/..
unzip qpdf-external-libs-src.zip
tar xzf external-libs-src/jpegsrc*
cd jpeg-*
./configure
make -k
sudo make install
cd ..
./configure --enable-werror --enable-show-failed-test-output
make -j$(nproc) -k
make -k check
