#!/bin/bash
set -ex
sudo apt-get update
sudo apt-get -y install \
   autoconf build-essential zlib1g-dev libjpeg-dev libgnutls28-dev \
   libssl-dev libtiff-tools ghostscript
./configure --enable-werror \
    --enable-crypto-native --enable-crypto-openssl --enable-crypto-gnutls \
    --enable-show-failed-test-output --enable-test-compare-images
make -j$(nproc) -k
for i in $(./qpdf/build/qpdf --show-crypto); do
    echo "*** Running tests with crypto provider $i"
    env QPDF_CRYPTO_PROVIDER=$i make -k check
done
export TMPDIR=$PWD/dist-tmp
rm -rf $TMPDIR
./make_dist --ci
mkdir distribution
cp $TMPDIR/qpdf*-ci.tar.gz distribution
sha256sum distribution/*
