#!/bin/bash
set -ex
cd $(dirname $0)/..
unzip qpdf-external-libs-src.zip
tar xzf external-libs-src/jpegsrc*
cd jpeg-*
./configure
make -k
sudo make install
cd ..
cmake -S . -B build -DCI_MODE=1 -DCMAKE_BUILD_TYPE=Release
cmake --build build -j$(nproc) -- -k
(cd build; ctest --verbose)
