#!/bin/bash
set -ex
sudo apt-get update
sudo apt-get -y install \
   autoconf build-essential zlib1g-dev libjpeg-dev libgnutls28-dev \
   libssl-dev python3-pip texlive-latex-extra latexmk \
   inkscape imagemagick libtiff-tools ghostscript
pip3 install sphinx sphinx_rtd_theme
./configure --enable-werror --enable-doc-maintenance \
    --enable-crypto-native --enable-crypto-openssl --enable-crypto-gnutls \
    --enable-show-failed-test-output --enable-test-compare-images
make -j$(nproc) -k
for i in $(./qpdf/build/qpdf --show-crypto); do
    echo "*** Running tests with crypto provider $i"
    env QPDF_CRYPTO_PROVIDER=$i make -k check
done
export TMPDIR=$PWD/dist-tmp
rm -rf $TMPDIR
./make_dist --ci --no-tests
mkdir distribution
cp $TMPDIR/qpdf*-ci.tar.gz distribution
sha256sum distribution/*
