#!/bin/bash
set -ex
cd $(dirname $0)/..
wordsize=$1
tool=$2

declare -a cmake_xargs
declare -a ctest_xargs
if [[ $tool == mingw ]]; then
    pacman -Sy --noconfirm make base-devel tar zip unzip
    if [ ! -x /c/msys64/mingw$wordsize/bin/g++.exe ]; then
        if [[ $wordsize == 64 ]]; then
            pacman -Sy --noconfirm mingw-w64-x86_64-toolchain
        else
            pacman -Sy --noconfirm mingw-w64-i686-toolchain
        fi
    fi
    PATH="/c/msys64/mingw$wordsize/bin:$PATH"
    config=RelWithDebInfo
    cmake_xargs=(-- -k)
    g++ -v
elif [[ $tool == msvc ]]; then
    cl
    config=Release
    cmake_xargs=(--config $config)
    ctest_xargs=(-C $config)
fi

mkdir build distribution
unzip doc.zip
unzip qpdf-external-libs-bin.zip

cd build
../cmake-win $tool ci
cmake --build . -j$(nproc) "${cmake_xargs[@]}"
ctest --verbose "${ctest_xargs[@]}"
cpack -G NSIS -C $config
cpack -G ZIP -C $config
mv qpdf-*.exe qpdf-*.zip ../distribution
cd ..
sha256sum distribution/*
