name: vcpkg cache
on:
  # This intentionally doesn't run on pull requests -- see vcpkg in
  # README-maintainer.md.
  schedule:
    - cron: '12 4 * * 4'
  workflow_dispatch:
jobs:
  Build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        triplet:
          - x64-windows-static
          - x64-mingw-static
          - x86-windows-static
          - x86-mingw-static
          - arm64-windows-static
    steps:
      - name: 'Disable git autocrlf'
        shell: bash
        run: git config --global core.autocrlf input
      - uses: actions/checkout@v7
      - name: 'Build libraries'
        shell: cmd
        run: build-scripts/run-vcpkg.bat ${{ matrix.triplet }}
      - name: 'Upload staged files'
        uses: actions/upload-artifact@v7
        with:
          name: vcpkg-${{ matrix.triplet }}
          path: vcpkg/installed/${{ matrix.triplet }}
  Package:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v7
      - name: 'Download x64-windows-static stage'
        uses: actions/download-artifact@v8
        with:
          name: vcpkg-x64-windows-static
          path: vcpkg/installed/x64-windows-static
      - name: 'Download x64-mingw-static stage'
        uses: actions/download-artifact@v8
        with:
          name: vcpkg-x64-mingw-static
          path: vcpkg/installed/x64-mingw-static
      - name: 'Download x86-windows-static stage'
        uses: actions/download-artifact@v8
        with:
          name: vcpkg-x86-windows-static
          path: vcpkg/installed/x86-windows-static
      - name: 'Download x86-mingw-static stage'
        uses: actions/download-artifact@v8
        with:
          name: vcpkg-x86-mingw-static
          path: vcpkg/installed/x86-mingw-static
      - name: 'Download arm64-windows-static stage'
        uses: actions/download-artifact@v8
        with:
          name: vcpkg-arm64-windows-static
          path: vcpkg/installed/arm64-windows-static
      - name: 'Package'
        run: build-scripts/package-vcpkg
        env:
          GH_TOKEN: ${{ github.token }}
      - name: 'Upload results'
        uses: actions/upload-artifact@v7
        with:
          name: vcpkg-win
          path: dist
