#!/bin/bash
set -ex
sudo apt-get update
sudo apt-get -y install \
   autoconf build-essential zlib1g-dev libjpeg-dev \
   docbook-xsl fop xsltproc libxml2-utils inkscape imagemagick
./configure --enable-werror --enable-doc-maintenance \
    --enable-show-failed-test-output
make -j$(nproc)
make -k check
make distfiles.zip
./make_dist --ci-mode --no-tests
mkdir distribution
cp /tmp/qpdf*-ci.tar.gz distribution
sha256sum distribution/*
